### ISSUE TITLE
DEM scale for watershed spatial covariates

### ISSUE THREAD

**Issue by rsshaftel** [rsshaftel/AKSSF#1]
The best way I know how to calculate spatial covariates across the stream network is using the weighted flow accumulation tool, which relies on the flow direction grid (fdr). Since the fdr are at the cell size and extent of each stream network processing area, we'll want to use the DEM that each network is created from for any spatial covariates that rely on that tool.
- for NHDPlus, that would be the elev_cm grid for each HUC8. For the synthetic networks, it would be the 10 m DEM.
- other watershed metrics, like percent glacier area, would need to be converted to the same cell size, extent, and snapping as the original DEM.
The only problem with this is that now we are created spatial covariates at different scales for our analysis, but I don't see a very easy way around this because we need whatever rasters we are using for our weights to match the cell size, extent, snapping, etc. of the flow direction grids.

**Comment by Dwmerrigan** [comment]
We have decided to resample the NHDPlus DEM to a 10mx10m grid to match the resolution of DEM coverage that is available for the rest of the study area.
