### ISSUE TITLE
Assigning spatial covariates to catchments

### ISSUE THREAD

**Issue by rsshaftel** [rsshaftel/AKSSF#3]
All spatial covariates should be assigned to catchments for each stream network processing area. I think this was resolved in past work for the Deshka and Anchor, but would be good to track here. An inner buffer on the catchments guarantees that statistics assigned along the flow network (e.g. percent glacier area) are extracted from the stream reach within the catchment and not a stream reach joining a catchment boundary.

**Comment by Dwmerrigan** [comment]
Using zonal statistics as table, tabulate area, tabulate intersection and iterating over individual catchments/watersheds where necessary to calculate covariates.  All cats/wtds have been given a unique identifier, cat_ID_con, that can be used to query the covariates and link them back to the sites.
